auto_user_role.auto_role_entity.*:
  type: config_entity
  label: 'Auto role config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    role:
      type: string
      label: 'Role'
    field:
      type: string
      label: 'Field'
    field_value:
      type: string
      label: 'Field value'
    uuid:
      type: string
